KaroKids/KaroKids_FrontEnd

src/App.jsx, src/components/Home/Landing.jsx
=> Add: Landing component template basic done

src/components/SocialBar.jsx
- Fixed sidebar visibility
- Sidebar rounded corners
- Sidebar responsive
=> Sidebar fixed

package-lock.json, package.json, src/components/ProductDetail/ProductDetail.jsx, src/components/ui/button.jsx, src/components/ui/combobox.jsx, src/components/ui/command.jsx, src/components/ui/dialog.jsx, src/components/ui/popover.jsx
=> Detail feature

src/App.jsx, src/components/SidebarSocial/SideBarSocial.jsx
- Fixed Sidebar name
- Fixed Sidebar place and border radius
=> Sidebar Social Fixed

src/components/ProductDetail/ProductDetail.jsx
*added carrousel and servicesDetail
* fix details
=> fix problems

src/components/CreateProduct/CreateProduct.jsx, src/utils/validation.js
* Added component CreateProduct
*  Styles basic
*
=> add create

src/components/Services/ServicesDetail.jsx
- Textos alineados y responsive
=> ServicesDetail complete

src/components/ProductDetail/ProductDetail.jsx
* Se saco el zoom por el momento
* Se agrando un poco la imagen
=> Cambio en imagen detalle

src/components/Home/BoyGirl.jsx, src/components/Home/Hero.jsx, src/components/Navbar/NavbarDesktop.jsx, src/components/Navbar/NavbarMobile.jsx, src/components/ProductList/ProductCard.jsx, src/components/ProductList/ProductList.jsx
- 1 parte de la integracion de la etiqueta Link
=> Temp Links

src/App.jsx, src/components/CreateProduct/CreateProduct.jsx, src/components/Navbar/NavbarDesktop.jsx, src/components/Navbar/NavbarMobile.jsx, src/components/ProductDetail/ProductDetail.jsx
*Links in detail
*Add a button AddProduct
=> Fixed detail navbar

src/components/Navbar/NavbarDesktop.jsx, src/components/Navbar/NavbarMobile.jsx, src/components/ProductDetail/ProductDetail.jsx, src/components/ProductList/ProductList.jsx, src/redux/productosActions.js, src/redux/productosSlice.js
* Add redux to detail
* Change styles to detail
* Fix Navbar
=> add redux to detail

src/components/Footer/Footer-Body.jsx, src/components/SidebarSocial/SideBarSocial.jsx
- Se modificó el renderizado del footer para que al entrar en mobile, el map se muestre por encima de todo
- Se modificó la altura de la Sidebar, asi como su tamaño en mobile.
=> Map footer & SideBar Mobile

src/components/ProductList/PaginationControls.jsx
- Se arreglo el error con los botones de paginados en mobile.
- Se agregó un window.scroll para que te deslice al inicio de la pagina una vez cambiada la pagina, con un movimiento suave.
=> Pagination buttons

public/assets/navbar-icons/back.svg, public/assets/navbar-icons/google.svg, public/assets/navbar-icons/user.svg, src/components/Auth/Login.jsx, src/components/Auth/Register.jsx, src/components/Navbar/NavbarDesktop.jsx, src/components/Navbar/NavbarMobile.jsx
* Se agrego el register
* se hizo responsive
* se agrego boton a la navbar mobile de user
=> se modifico el register y la nav

src/components/Auth/Login.jsx, src/components/Auth/Register.jsx, src/components/Navbar/NavbarDesktop.jsx, src/components/Navbar/NavbarMobile.jsx, src/components/User/UserModal.jsx, src/components/ui/button.jsx, src/context/AuthContext.jsx
- Added UserModal for User Info and User Logout
- Fixed Alert for register and login
- Added displayName for createUserWithEmailAndPassword
=> FireBase UserData

src/components/CreateProduct/CreateProduct.jsx, src/components/UploadImage/UploadImage.jsx, src/utils/validation.js
Product.jsx, component, send data to backend ready.
=> add: Product.jsx, send data to backend done

src/components/Auth/Login.jsx, src/components/Auth/Register.jsx, src/components/Navbar/NavbarDesktop.jsx, src/components/Navbar/NavbarMobile.jsx, src/components/ProductList/FilterOptions.jsx, src/components/ProductList/ProductList.jsx, src/components/User/UserModal.jsx
*Se suavizo la vista de modales
*de filtros, login, menu hamburguesa
=> cambios en despliegues de modales

src/App.jsx, src/components/SearchBar/SearchBar.jsx, src/components/User/PanelUsuario.jsx
* Se agrego componente panelUsuario
* Se modifico la busqueda de la searchbar
=> searchbar y componente panelUsuario

public/assets/panel-icons/carrito.svg, public/assets/panel-icons/data-personal.svg, public/assets/panel-icons/user-profile.svg, src/components/Navbar/NavbarMobile.jsx, src/components/User/ControlView.jsx, src/components/User/PanelUsuario.jsx, src/components/User/UserModal.jsx
* Agregado el componente controlView
* Se fixeo la barra de busqueda del nav mobile
=> se agrego controlView y se fixeo la navbar mobile

src/components/Auth/Login.jsx, src/components/Auth/Register.jsx, src/components/ProductDetail/ProductDetail.jsx, src/components/User/ControlView.jsx, src/context/AuthContext.jsx
- Added Reset Password for login ForgetPassword
=> ResetPasswordEmail

src/App.jsx, src/components/Home/Landing.jsx, src/components/ProtectedRoute/ProtectedRoute.jsx, src/context/AuthContext.jsx
=> protected routes

src/components/ProductDetail/ProductDetail.jsx
*Se cambio el renderizado de los talles, y la logica de colores y talles
*Se cambiaron estilos
=> cambio logica talles y colores

src/components/Cart/ProductCart.jsx, src/components/ProductDetail/ProductDetail.jsx, src/redux/carritoSlice.js
=> trabajando en ProductCart y carritoSlice

src/components/Cart/Cart.jsx, src/components/Navbar/NavbarDesktop.jsx, src/components/ProductDetail/ProductDetail.jsx
* ProductDetail para que la cantidad no pueda ser 0
* Cart solamente agregue un link
* navbar LINK
=> cambios en productDetail, cart y navbarDesktop

src/components/Auth/Register.jsx, src/components/User/DatosPersonales.jsx, src/redux/userAction.js, src/redux/userSlice.js
* Se agrego la modificacion del usuario
=> se agrego la funcionalidad de modificar usuario

src/components/Admin/UsersView.jsx, src/components/CreateProduct/CreateProduct.jsx, src/components/UploadImage/UploadImage.jsx, src/utils/validation.js
se reparo el form de crear producto y el eliminar usuario
=> crear producto, eliminar usuario

src/components/ProductDetail/ProductDetail.jsx, src/components/ProductList/ProductList.jsx, src/redux/productosSlice.js
*Se agrego esqueleton de carga para productos y detail
* se borra el detail del estado 
* Se renderizan imagenes pequeñas debajo de la imagen cuando es responsive
=> se agrego skeleton para productos y detail

src/components/Admin/ProductsView.jsx, src/components/Home/Carrousel.jsx, src/components/Navbar/NavbarDesktop.jsx, src/components/Navbar/NavbarMobile.jsx, src/redux/productosActions.js
* Fixed errores admin
* Carrousel
=> fixed admin y carrousel destacados

src/components/Favorites/FavoriteProducts.jsx, src/components/ProductList/ProductCard.jsx, src/components/ProductList/ProductList.jsx
*Favoritos renderizados en el front
=> favoritos terminado

src/components/Admin/ProductsView.jsx, src/utils/saldoStock.js
Add:
- Agregado una columna de nombre "Stock" en la tabla de productos.
=> add: Columna de Stock en la tabla ProductsView

src/components/Navbar/NavbarDesktop.jsx, src/components/Navbar/NavbarMobile.jsx, src/components/Navbar/NavbarModal.jsx
* Se agrego el sub-menu de categorias por edad
* Se corrigio los li del menu hambuerguesa
=> modal categorias edad

src/components/Auth/Register.jsx, src/components/ProductList/ProductCard.jsx
- Se agregó un checkbox al register
- Se agrego una validación para que el usuario no se pueda registrar si no acepta los términos y condiciones
-Se resolvió el bug del paginado respecto a los Favoritos
=> Acepto los terminos

src/components/ProductList/ProductCard.jsx
Se elimino un useEffect innecesario
=> Favorite Fixed

src/components/Admin/ProductsView.jsx, src/components/Admin/UsersView.jsx, src/components/Auth/Register.jsx, src/components/Auth/validator.js, src/components/ProductList/ProductList.jsx, src/redux/productosActions.js
**NO LO APRUEBEN** **NO LO APRUEBEN** **NO LO APRUEBEN** **NO LO APRUEBEN**
Validacion de Registro, Console.log eliminados, Mensaje cuando no se muestran productos/usuarios
Modifique el Register, el ProductList, ProductView y UserView
=> Bugs y correcciones

package-lock.json, package.json, src/components/UploadImage/UploadImage.jsx, src/utils/heicToJpeg.js
- Se creó una utilidad con la función necesaria para convertir los archivos de imagen HEIC en archivos JPEG.
- Se implementó la función en el componente "UploadImage"
- Queda pendiente la prueba y la implementación en el componente "UploadImageEdit"
=> implementacion de conversor de archivos

src/components/CreateProduct/EditProduct.jsx, src/components/CreateProduct/UploadImageEdit.jsx, src/redux/productosActions.js
Fix carga de imagenes secundarias y delete imagenes secundarias.
=> add: Fix carga de imagenes secundarias y delete imagenes secundarias

package-lock.json, package.json, src/App.jsx, src/components/OrderDetail/OrderDetail.jsx, src/components/OrderDetail/OrderModal.jsx, src/components/Reviews/StarRating.jsx, src/components/User/UserPedidos.jsx, src/redux/store.js, src/redux/userAction.js, src/redux/userSlice.js
Tambien se añadio descarga en PDF de la orden by @LGKaufmann
=> detalle de orden + review a productos comprados en la orden

src/components/CreateProduct/UploadImageEdit.jsx, src/components/UploadImage/UploadImage.jsx, src/utils/convertFromHeic.js
- Se volvió a instalar la dependencia y a crear la utilidad necesaria para coonvertir las imágenes en formato .heic a .jpeg
- Se solucionaron problemas previos vinculados a la implementación de la funcionalidad.
- Se modificaron los componentes "UploadImage" y "UploadImageEdit" para implementar la funcionalidad previo al proceso de hasheo de las imágenes a Base64.
- Se modificaron y/o añadieron algunos detalles de renderizado vinculados al proceso de carga y conversión de las imágenes principal y secundarias.
=> Modificaciones en los componentes vinculados a imagenes

public/assets/navbar-icons/whatsapp.svg, src/components/Admin/FiltersOrder.jsx, src/components/Admin/NavBarDeskTopDB.jsx, src/components/Admin/OrderPagination.jsx, src/components/Admin/Orders.jsx, src/components/Cart/Cart.jsx, src/components/Home/Carrousel.jsx, src/redux/ordenesActions.js, src/redux/ordenesSlice.js
*fixed boton de whatsapp con estilos
*Arreglado la navbar, el ordenamiento, filtros y searchbar de ordenes'
=> fixed estilos boton wpp y ordenes filtros, ordenamientos

src/components/Admin/FiltersOrder.jsx, src/components/Admin/FiltersProduct.jsx, src/components/Admin/FiltersUser.jsx, src/components/Admin/OrderPagination.jsx, src/components/Admin/Orders.jsx, src/components/Admin/ProductsView.jsx, src/components/Admin/UserPagination.jsx, src/components/Admin/UsersView.jsx, src/components/ProductList/FilterOptions.jsx, src/components/ProductList/ProductList.jsx, src/components/SearchBar/SearchBar.jsx, src/redux/ordenesActions.js, src/redux/ordenesSlice.js, src/redux/userAction.js, src/redux/userSlice.js
=> se combinan todos searchbar, filtros y ordenaminetos de TODAS las vistas
